In [75]:
import numpy as np
from numpy.linalg import inv
import time

In [55]:
A = np.array([[10, 3, 0],
             [3, 15, 1],
             [0, 1, 7]], float)
f  = np.array([2, 12, 5], float)
A2 = np.triu(A, 1)
A1 = np.tril(A, -1)
D = np.diag(np.diag(A))

array([-0.0296827 ,  0.76560901,  0.604913  ])

In [84]:
# Метод Якоби
tic = time.perf_counter()
x = np.ones_like(f)
while np.sqrt(np.sum((f - A @ x) ** 2))/(np.sqrt(np.sum(f ** 2))) > 10 ** -4:
  x = -inv(D) @ A1 @ x - inv(D) @ A2 @ x + inv(D) @ f
print(x)
toc = time.perf_counter()
print("Время потраченное на выполнение: ", toc-tic)

[-0.02965929  0.76561448  0.60492415]
Время потраченное на выполнение:  0.004696024000168109


In [81]:
# метод Гаусса-Зейделя
tic = time.perf_counter()
x = np.ones_like(f)
while np.sqrt(np.sum((f - A @ x) ** 2))/(np.sqrt(np.sum(f ** 2))) > 10 ** -4:
  x = inv(D + A1) @ (f - A2 @ x)
print(x)

toc = time.perf_counter()
print("Время потраченное на выполнение: ", toc-tic)

[-0.0296649   0.76560488  0.60491359]
Время потраченное на выполнение:  0.0008191960000658582


In [91]:
# метод SOR
tic = time.perf_counter()
x = np.ones_like(f)
w = 0.5

while np.sqrt(np.sum((f - A @ x) ** 2))/(np.sqrt(np.sum(f ** 2))) > 10 ** -4:
  x = inv(np.eye(len(f)) + w * inv(D) @ A1) @ (((1 - w) * np.eye(len(f)) - w * inv(D) @ A2) @ x + w * inv(D) @ f)
print(x)

toc = time.perf_counter()
print("Время потраченное на выполнение: ", toc-tic)

[-0.02958669  0.76554329  0.6049431 ]
Время потраченное на выполнение:  0.007214432999717246
