In [370]:
import numpy as np
from numpy import linalg
import sympy as sp
from sympy import *
# Подготовка

A = Matrix([[2, 1, -3],
            [0, 1, -1],
            [0, -2, 2]])
x = Symbol('x')
eigenv_start = [-1, 0, 2]
print(eigenv_start)
matrix = A - eye(sqrt(len(A))) * x
det_expr1 = matrix.det()
det_diff1 = diff(det_expr1)
det_expr = lambdify(x, det_expr1)
det_diff = lambdify(x, det_diff1)
print(matrix)

[-1, 0, 2]
Matrix([[2 - x, 1, -3], [0, 1 - x, -1], [0, -2, 2 - x]])


In [371]:
#Собственные значения и вектора методом Ньютона
def Newton(eigenv_start, matrix, n):
  for step in range(n):
    eigenv_start = eigenv_start - det_expr(eigenv_start) / det_diff(eigenv_start)
  return eigenv_start


for i in range(len(eigenv_start)):
  m = 0
  eigenv_start[i]= Newton(eigenv_start[i], matrix, 100)
  if (eigenv_start[i] - eigenv_start[i - 1]) ** 2 < 10 ** -4 and i > 0:
   while (eigenv_start[i] - eigenv_start[i - 1]) ** 2 < 10 ** -4:
     m += 0.5
     eigenv_start[i] += m
     eigenv_start[i]= Newton(eigenv_start[i], matrix, 100)

print(eigenv_start)

[0.0, 3.0, 2.0]


In [348]:
#Собственные вектора методом Якоби
def Jacoby(x, A1, A2, D, n):
  for i in range(n):
    x = -linalg.inv(D) @ A1 @ x - linalg.inv(D) @ A2 @ x
    norm = np.linalg.norm(x)
  return x /norm

In [349]:
#Собственные вектора методом Зейделя
def Zeydel(x, A1, A2, D, n):
  for i in range(n):
    x = linalg.inv(D + A1) @ A2 @ x
    norm = np.linalg.norm(x)
  return x /norm

In [350]:
#Собственные вектора методом SOR
def SOR(x, A1, A2, D, n, w):
  I = np.eye(sqrt(len(A)))
  for i in range(n):
    x = -linalg.inv(I + w * linalg.inv(D) @ A1) @ ((1 - w) * I - w * linalg.inv(D) @ A2) @ x
    norm = np.linalg.norm(x)
  return x /norm

In [351]:
x = np.ones(sqrt(len(A)))

for i in eigenv_start:
  new_matrix = np.array(A, float) - np.eye(sqrt(len(A))) * i
  A1 = np.tril(new_matrix, k=-1)
  A2 = np.triu(new_matrix, k=1)
  D = np.eye(sqrt(len(A))) * new_matrix
  print('Для собственного числа {0:.3f}'.format(i))
  print('Метод Якоби: ', Jacoby(x, A1, A2, D, 50))
  print('---------------------')
  print('Метод Зейделя: ', Zeydel(x, A1, A2, D, 20))
  print('---------------------')
  print('Метод SOR: ', SOR(x, A1, A2, D, 20, 1))
  print('=====================')

Для собственного числа -2.000
Метод Якоби:  [0.63960215 0.42640143 0.63960215]
---------------------
Метод Зейделя:  [-2.13190511e-08 -4.47213587e-01  8.94427195e-01]
---------------------
Метод SOR:  [-2.13190511e-08 -4.47213587e-01  8.94427195e-01]
Для собственного числа 4.000
Метод Якоби:  [-0.51449576  0.68599434 -0.51449576]
---------------------
Метод Зейделя:  [-0.97049496  0.21566555 -0.10783277]
---------------------
Метод SOR:  [-0.97049496  0.21566555 -0.10783277]
Для собственного числа 2.000
Метод Якоби:  [-0.40824829  0.81649658 -0.40824829]
---------------------
Метод Зейделя:  [-8.94427191e-01  4.47213596e-01  5.13038426e-11]
---------------------
Метод SOR:  [-8.94427191e-01  4.47213596e-01  5.13038426e-11]


In [354]:
# Программно
B = np.array(A, float) * 1
w, v = np.linalg.eig(B)
print(w)
print(v)

[5. 5. 3.]
[[ 1.          0.          0.57735027]
 [ 0.          0.70710678  0.57735027]
 [ 0.         -0.70710678  0.57735027]]


In [149]:
A = np.array([[16, 3, 2],
            [3, 5, 1],
            [2, 1, 10]], float)
B = np.array([0, 0, 1])
print(linalg.solve(A, B))

[-0.01020408 -0.01457726  0.10349854]
