In [8]:
import numpy as np
from numpy import linalg
import sympy as sp
from sympy import *
# Подготовка
A = Matrix([[3, 7, 3],
            [7, 7, 4],
            [3, 4, 15]])
x = Symbol('x')
matrix = A - eye(sqrt(len(A))) * x
det_expr1 = matrix.det()
det_diff1 = diff(det_expr1)
det_expr = lambdify(x, det_expr1)
det_diff = lambdify(x, det_diff1)
print(matrix)

Matrix([[3 - x, 7, 3], [7, 7 - x, 4], [3, 4, 15 - x]])


In [9]:
# Приближение
eigenv_start = []
x_trace = np.linspace(-100, 100, 1000)
for i in range(1, len(x_trace)):
  if det_expr(x_trace[i]) * det_expr(x_trace[i - 1]) < 0:
    eigenv_start.append(x_trace[i - 1])
print(eigenv_start)

[-2.3023023023022944, 8.308308308308312, 18.71871871871872]


In [10]:
#Собственные значения и вектора методом Ньютона
def Newton(eigenv_start, matrix, n):
  for step in range(n):
    eigenv_start = eigenv_start - det_expr(eigenv_start) / det_diff(eigenv_start)
  return eigenv_start


for i in range(len(eigenv_start)):
  m = 0
  eigenv_start[i]= Newton(eigenv_start[i], matrix, 100)
  if (eigenv_start[i] - eigenv_start[i - 1]) ** 2 < 10 ** -4 and i > 0:
   while (eigenv_start[i] - eigenv_start[i - 1]) ** 2 < 10 ** -4:
     m += 1
     eigenv_start[i] += m
     eigenv_start[i]= Newton(eigenv_start[i], matrix, 100)

print(eigenv_start)

[-2.280122012849309, 8.458434085825909, 18.8216879270234]


In [11]:
#Собственные вектора методом Якоби
def Jacoby(x, A1, A2, D, n):
  for i in range(n):
    x = -linalg.inv(D) @ A1 @ x - linalg.inv(D) @ A2 @ x
    norm = np.linalg.norm(x)
  return x /norm

In [12]:
#Собственные вектора методом Зейделя
def Zeydel(x, A1, A2, D, n):
  for i in range(n):
    x = linalg.inv(D + A1) @ A2 @ x
    norm = np.linalg.norm(x)
  return x /norm

In [13]:
#Собственные вектора методом SOR
def SOR(x, A1, A2, D, n, w):
  I = np.eye(sqrt(len(A)))
  for i in range(n):
    x = -linalg.inv(I + w * linalg.inv(D) @ A1) @ ((1 - w) * I - w * linalg.inv(D) @ A2) @ x
    norm = np.linalg.norm(x)
  return x /norm

In [14]:
x = np.ones(sqrt(len(A)))

for i in eigenv_start:
  new_matrix = np.array(A, float) - np.eye(sqrt(len(A))) * i
  A1 = np.tril(new_matrix, k=-1)
  A2 = np.triu(new_matrix, k=1)
  D = np.eye(sqrt(len(A))) * new_matrix
  print('Для собственного числа {0:.3f}'.format(i))
  print('Метод Якоби: ', Jacoby(x, A1, A2, D, 30))
  print('---------------------')
  print('Метод Зейделя: ', Zeydel(x, A1, A2, D, 20))
  print('---------------------')
  print('Метод SOR: ', SOR(x, A1, A2, D, 20, 1))
  print('=====================')

Для собственного числа -2.280
Метод Якоби:  [0.77599697 0.58679127 0.23131086]
---------------------
Метод Зейделя:  [-0.79816578  0.60243722 -0.00088261]
---------------------
Метод SOR:  [-0.79816578  0.60243722 -0.00088261]
Для собственного числа 8.458
Метод Якоби:  [ 0.49546047 -0.85941998 -0.1261595 ]
---------------------
Метод Зейделя:  [ 0.36149238  0.71246079 -0.60143402]
---------------------
Метод SOR:  [ 0.36149238  0.71246079 -0.60143402]
Для собственного числа 18.822
Метод Якоби:  [0.36527992 0.48512141 0.79449846]
---------------------
Метод Зейделя:  [0.36527993 0.48512137 0.79449848]
---------------------
Метод SOR:  [0.36527993 0.48512137 0.79449848]


In [15]:
# Программно
B = np.array(A, float) * 1
w, v = np.linalg.eig(B)
print(w)
print(v)

[18.82168793 -2.28012201  8.45843409]
[[-0.36527993 -0.79816578 -0.47906363]
 [-0.48512137  0.60243722 -0.6338191 ]
 [-0.79449848 -0.00088261  0.6072655 ]]


In [ ]:
A = np.array([[16, 3, 2],
            [3, 5, 1],
            [2, 1, 10]], float)
B = np.array([0, 0, 1])
print(linalg.solve(A, B))

[-0.01020408 -0.01457726  0.10349854]
